// Daftar negara dan kota lengkap (141 negara, 900+ kota)
// Data dikurasi dari sumber publik

const Map<String, List<String>> kotaByNegara = {
  'Afghanistan': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad'],
  'Albania': ['Tirana', 'Durres', 'Vlore', 'Shkoder', 'Fier', 'Elbasan'],
  'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Setif'],
  'Angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Namibe'],
  'Argentina': ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucuman', 'Mar del Plata', 'Salta'],
  'Armenia': ['Yerevan', 'Gyumri', 'Vanadzor'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Darwin', 'Hobart', 'Gold Coast', 'Newcastle'],
  'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck'],
  'Azerbaijan': ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir'],
  'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town'],
  'Bangladesh': ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Comilla'],
  'Belarus': ['Minsk', 'Gomel', 'Vitebsk', 'Mogilev', 'Grodno', 'Brest'],
  'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liege', 'Namur'],
  'Bhutan': ['Thimphu', 'Phuntsholing', 'Paro'],
  'Bolivia': ['Santa Cruz', 'La Paz', 'Cochabamba', 'Oruro', 'Sucre'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar'],
  'Brazil': ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belem', 'Goiania'],
  'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong'],
  'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Rousse', 'Stara Zagora'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora'],
  'Cambodia': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham'],
  'Cameroon': ['Yaounde', 'Douala', 'Garoua', 'Bamenda', 'Bafoussam', 'Maroua'],
  'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Brampton', 'Surrey', 'Halifax'],
  'Chile': ['Santiago', 'Valparaiso', 'Concepcion', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua'],
  'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Nanjing', 'Tianjin', 'Chongqing', 'Dongguan', 'Foshan', 'Shenyang'],
  'Colombia': ['Bogota', 'Medellin', 'Cali', 'Barranquilla', 'Cartagena', 'Cucuta', 'Bucaramanga'],
  'Costa Rica': ['San Jose', 'Alajuela', 'Desamparados', 'Cartago', 'Heredia'],
  'Cote d\'Ivoire': ['Abidjan', 'Bouake', 'Daloa', 'Yamoussoukro', 'San-Pedro'],
  'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik'],
  'Cuba': ['Havana', 'Santiago de Cuba', 'Holguin', 'Camaguey', 'Santa Clara'],
  'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc'],
  'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg'],
  'Dominican Republic': ['Santo Domingo', 'Santiago', 'Santo Domingo Este', 'La Romana'],
  'Ecuador': ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala'],
  'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Aswan'],
  'El Salvador': ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos'],
  'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Parnu', 'Kohtla-Jarve'],
  'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Awasa', 'Bahir Dar'],
  'Fiji': ['Suva', 'Lautoka', 'Nadi', 'Labasa'],
  'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku'],
  'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille'],
  'Georgia': ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi'],
  'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen', 'Dresden'],
  'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Tema', 'Obuasi'],
  'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Rhodes'],
  'Guatemala': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango'],
  'Haiti': ['Port-au-Prince', 'Cap-Haitien', 'Delmas', 'Petionville'],
  'Honduras': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Mong Kok', 'Tsuen Wan'],
  'Hungary': ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pecs', 'Gyor'],
  'Iceland': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri'],
  'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Bhopal', 'Patna', 'Vadodara', 'Visakhapatnam'],
  'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Yogyakarta', 'Palembang', 'Denpasar', 'Tangerang', 'Depok', 'Bekasi', 'Bogor', 'Batam', 'Pekanbaru'],
  'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom'],
  'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk', 'Najaf', 'Sulaymaniyah'],
  'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda'],
  'Israel': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod'],
  'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Catania', 'Venice'],
  'Jamaica': ['Kingston', 'Spanish Town', 'Montego Bay', 'Portmore'],
  'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Sapporo', 'Nagoya', 'Fukuoka', 'Hiroshima', 'Yokohama', 'Kobe', 'Sendai', 'Kawasaki', 'Saitama'],
  'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Russeifa'],
  'Kazakhstan': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi'],
  'Kosovo': ['Pristina', 'Prizren', 'Peja', 'Gjakova', 'Gjilan'],
  'Kuwait': ['Kuwait City', 'Hawalli', 'Salmiya', 'Ahmadi'],
  'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad'],
  'Laos': ['Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet'],
  'Latvia': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava', 'Jurmala'],
  'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh'],
  'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Sirte'],
  'Lithuania': ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys'],
  'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange'],
  'Macau': ['Macau'],
  'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa'],
  'Malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Malaka', 'Kota Kinabalu', 'Kuching', 'Shah Alam', 'Petaling Jaya', 'Klang'],
  'Maldives': ['Male', 'Addu City', 'Fuvahmulah'],
  'Mali': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Segou'],
  'Malta': ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Zabbar'],
  'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Leon', 'Juarez', 'Zapopan', 'Merida', 'Cancun', 'Acapulco'],
  'Moldova': ['Chisinau', 'Tiraspol', 'Balti', 'Bender'],
  'Mongolia': ['Ulaanbaatar', 'Darkhan', 'Erdenet'],
  'Montenegro': ['Podgorica', 'Niksic', 'Pljevlja', 'Bijelo Polje'],
  'Morocco': ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Agadir', 'Tangier', 'Meknes', 'Oujda'],
  'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio'],
  'Myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Bago', 'Mawlamyine', 'Taunggyi'],
  'Nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj'],
  'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier', 'Dunedin'],
  'Niger': ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez'],
  'Nigeria': ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Kaduna', 'Enugu'],
  'North Macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo', 'Ohrid'],
  'Norway': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen'],
  'Oman': ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur'],
  'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Quetta'],
  'Palestine': ['Gaza', 'Ramallah', 'Hebron', 'Nablus', 'Bethlehem'],
  'Panama': ['Panama City', 'San Miguelito', 'Tocumen', 'David'],
  'Papua New Guinea': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 'Goroka'],
  'Paraguay': ['Asuncion', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiata'],
  'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco'],
  'Philippines': ['Manila', 'Quezon City', 'Cebu City', 'Davao', 'Makati', 'Baguio', 'Iloilo', 'Pasig', 'Zamboanga', 'Cagayan de Oro'],
  'Poland': ['Warsaw', 'Krakow', 'Lodz', 'Wroclaw', 'Poznan', 'Gdansk', 'Szczecin', 'Katowice'],
  'Portugal': ['Lisbon', 'Porto', 'Braga', 'Setubal', 'Coimbra', 'Funchal'],
  'Puerto Rico': ['San Juan', 'Bayamon', 'Carolina', 'Ponce', 'Caguas'],
  'Qatar': ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor'],
  'Romania': ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi', 'Constanta', 'Craiova', 'Brasov'],
  'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Ufa', 'Rostov-on-Don', 'Krasnoyarsk', 'Perm', 'Voronezh', 'Volgograd', 'Krasnodar'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Taif', 'Buraidah'],
  'Senegal': ['Dakar', 'Touba', 'Thies', 'Rufisque', 'Kaolack'],
  'Serbia': ['Belgrade', 'Novi Sad', 'Nis', 'Kragujevac', 'Subotica'],
  'Singapore': ['Singapore'],
  'Slovakia': ['Bratislava', 'Kosice', 'Presov', 'Zilina', 'Banska Bystrica'],
  'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj'],
  'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Merca'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Soweto'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam'],
  'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Murcia', 'Palma', 'Bilbao', 'Alicante'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo'],
  'Sudan': ['Khartoum', 'Omdurman', 'Khartoum North', 'Port Sudan', 'Kassala'],
  'Sweden': ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Vasteras', 'Orebro'],
  'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur'],
  'Syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama'],
  'Taiwan': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Taoyuan', 'Keelung'],
  'Tajikistan': ['Dushanbe', 'Khujand', 'Kulob'],
  'Tanzania': ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro'],
  'Thailand': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Khon Kaen', 'Nakhon Ratchasima', 'Udon Thani', 'Chiang Rai'],
  'Timor-Leste': ['Dili', 'Baucau', 'Maliana'],
  'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan'],
  'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Antalya', 'Konya', 'Trabzon'],
  'Turkmenistan': ['Ashgabat', 'Turkmenabat', 'Mary'],
  'Uganda': ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja'],
  'Ukraine': ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Mykolaiv'],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah'],
  'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Leeds', 'Liverpool', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff', 'Belfast', 'Newcastle'],
  'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'San Francisco', 'Columbus', 'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Washington', 'Nashville', 'Boston', 'Portland', 'Las Vegas', 'Miami', 'Atlanta'],
  'Uruguay': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandu'],
  'Uzbekistan': ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Bukhara'],
  'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay'],
  'Vietnam': ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho', 'Hue', 'Nha Trang', 'Vung Tau', 'Bien Hoa'],
  'Yemen': ['Sanaa', 'Aden', 'Taiz', 'Hodeidah', 'Ibb'],
  'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru'],
};

/// 250 negara lengkap untuk filter online users
const List<String> allCountries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Belarus',
  'Belgium',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Costa Rica',
  'Cote d\'Ivoire',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Guatemala',
  'Haiti',
  'Honduras',
  'Hong Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Libya',
  'Lithuania',
  'Luxembourg',
  'Macau',
  'Madagascar',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Mexico',
  'Moldova',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Niger',
  'Nigeria',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Puerto Rico',
  'Qatar',
  'Romania',
  'Russia',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Somalia',
  'South Africa',
  'South Korea',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zimbabwe',
];

/// Mendapatkan list kota untuk negara tertentu
List<String> getCitiesForCountry(String country) =>
    kotaByNegara[country] ?? [];

/// Mendapatkan nama negara (kompatibilitas dengan entry_screen)
String negaraLabel(String key, bool isId) => key;

/// Mendapatkan list negara yang punya data kota
List<String> getNegaraKeys() => kotaByNegara.keys.toList();
