// Daftar negara dan kota lengkap
// Data dikurasi dari sumber publik

const Map<String, List<String>> kotaByNegara = {
  'Afghanistan': ['Ghazni', 'Herat', 'Jalalabad', 'Kabul', 'Kandahar', 'Kunduz', 'Lashkar Gah', 'Mazar-i-Sharif'],
  'Albania': ['Berat', 'Durres', 'Elbasan', 'Fier', 'Korce', 'Shkoder', 'Tirana', 'Vlore'],
  'Algeria': ['Algiers', 'Annaba', 'Batna', 'Blida', 'Constantine', 'Djelfa', 'Oran', 'Setif', 'Sidi Bel Abbes'],
  'Angola': ['Benguela', 'Cabinda', 'Huambo', 'Lobito', 'Luanda', 'Lubango', 'Namibe'],
  'Argentina': ['Buenos Aires', 'Cordoba', 'Corrientes', 'La Plata', 'Mar del Plata', 'Mendoza', 'Posadas', 'Resistencia', 'Rosario', 'Salta', 'San Juan', 'San Miguel de Tucuman', 'Santa Fe', 'Santiago del Estero'],
  'Armenia': ['Abovyan', 'Gyumri', 'Kapan', 'Vagharshapat', 'Vanadzor', 'Yerevan'],
  'Australia': ['Adelaide', 'Brisbane', 'Cairns', 'Canberra', 'Darwin', 'Geelong', 'Gold Coast', 'Hobart', 'Melbourne', 'Newcastle', 'Perth', 'Sydney', 'Toowoomba', 'Townsville', 'Wollongong'],
  'Austria': ['Dornbirn', 'Graz', 'Innsbruck', 'Klagenfurt', 'Linz', 'Salzburg', 'Sankt Polten', 'Vienna', 'Villach', 'Wels'],
  'Azerbaijan': ['Baku', 'Ganja', 'Lankaran', 'Mingachevir', 'Nakhchivan', 'Shirvan', 'Sumqayit'],
  'Bahrain': ['Aali', 'Hamad Town', 'Isa Town', 'Manama', 'Muharraq', 'Riffa', 'Sitra'],
  'Bangladesh': ['Barisal', 'Bogra', 'Chittagong', 'Comilla', 'Cox\'s Bazar', 'Dhaka', 'Khulna', 'Rajshahi', 'Rangpur', 'Sylhet'],
  'Belarus': ['Babruysk', 'Baranovichi', 'Brest', 'Gomel', 'Grodno', 'Minsk', 'Mogilev', 'Vitebsk'],
  'Belgium': ['Aalst', 'Antwerp', 'Bruges', 'Brussels', 'Ghent', 'Kortrijk', 'Leuven', 'Liege', 'Mons', 'Namur'],
  'Bhutan': ['Gelephu', 'Paro', 'Phuntsholing', 'Samdrup Jongkhar', 'Thimphu'],
  'Bolivia': ['Cochabamba', 'La Paz', 'Oruro', 'Potosi', 'Quillacollo', 'Sacaba', 'Santa Cruz', 'Sucre', 'Tarija'],
  'Bosnia and Herzegovina': ['Banja Luka', 'Bijeljina', 'Brcko', 'Mostar', 'Sarajevo', 'Trebinje', 'Tuzla', 'Zenica'],
  'Brazil': ['Aracaju', 'Belem', 'Belo Horizonte', 'Brasilia', 'Campinas', 'Campo Grande', 'Curitiba', 'Florianopolis', 'Fortaleza', 'Goiania', 'Guarulhos', 'Joao Pessoa', 'Maceio', 'Manaus', 'Natal', 'Porto Alegre', 'Recife', 'Rio de Janeiro', 'Salvador', 'Sao Luis', 'Sao Paulo', 'Sorocaba', 'Teresina', 'Uberlandia'],
  'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Temburong', 'Tutong'],
  'Bulgaria': ['Burgas', 'Dobrich', 'Pleven', 'Plovdiv', 'Rousse', 'Shumen', 'Sliven', 'Sofia', 'Stara Zagora', 'Varna'],
  'Burkina Faso': ['Banfora', 'Bobo-Dioulasso', 'Dedougou', 'Koudougou', 'Ouagadougou', 'Ouahigouya'],
  'Cambodia': ['Battambang', 'Kampong Cham', 'Kampong Chhnang', 'Kampot', 'Phnom Penh', 'Poipet', 'Siem Reap', 'Sihanoukville'],
  'Cameroon': ['Bafoussam', 'Bamenda', 'Douala', 'Ebolowa', 'Garoua', 'Kumba', 'Maroua', 'Ngaoundere', 'Yaounde'],
  'Canada': ['Brampton', 'Burnaby', 'Calgary', 'Edmonton', 'Gatineau', 'Halifax', 'Hamilton', 'Kitchener', 'London', 'Markham', 'Montreal', 'Ottawa', 'Quebec City', 'Regina', 'Saskatoon', 'Surrey', 'Toronto', 'Vancouver', 'Vaughan', 'Victoria', 'Windsor', 'Winnipeg'],
  'Chile': ['Antofagasta', 'Arica', 'Chillan', 'Concepcion', 'Iquique', 'La Serena', 'Osorno', 'Rancagua', 'Santiago', 'Talca', 'Temuco', 'Valparaiso'],
  'China': ['Beijing', 'Changsha', 'Chengdu', 'Chongqing', 'Dalian', 'Dongguan', 'Foshan', 'Fuzhou', 'Guangzhou', 'Guiyang', 'Hangzhou', 'Harbin', 'Hefei', 'Hohhot', 'Jinan', 'Kunming', 'Lanzhou', 'Nanjing', 'Nanning', 'Qingdao', 'Shanghai', 'Shenyang', 'Shenzhen', 'Tianjin', 'Urumqi', 'Wuhan', 'Xi\'an', 'Xiamen', 'Zhengzhou'],
  'Colombia': ['Armenia', 'Barranquilla', 'Bogota', 'Bucaramanga', 'Cali', 'Cartagena', 'Cucuta', 'Ibague', 'Manizales', 'Medellin', 'Neiva', 'Pasto', 'Pereira', 'Santa Marta', 'Villavicencio'],
  'Costa Rica': ['Alajuela', 'Cartago', 'Desamparados', 'Heredia', 'Liberia', 'Limon', 'Puntarenas', 'San Jose'],
  'Cote d\'Ivoire': ['Abidjan', 'Bouake', 'Daloa', 'Divo', 'Gagnoa', 'Korhogo', 'Man', 'San-Pedro', 'Yamoussoukro'],
  'Croatia': ['Dubrovnik', 'Karlovac', 'Osijek', 'Rijeka', 'Sibenik', 'Slavonski Brod', 'Split', 'Varazdin', 'Zadar', 'Zagreb'],
  'Cuba': ['Bayamo', 'Camaguey', 'Cienfuegos', 'Guantanamo', 'Havana', 'Holguin', 'Las Tunas', 'Pinar del Rio', 'Santa Clara', 'Santiago de Cuba'],
  'Cyprus': ['Famagusta', 'Kyrenia', 'Larnaca', 'Limassol', 'Nicosia', 'Paphos', 'Paralimni'],
  'Czech Republic': ['Brno', 'Ceske Budejovice', 'Hradec Kralove', 'Liberec', 'Olomouc', 'Ostrava', 'Pardubice', 'Plzen', 'Prague', 'Usti nad Labem'],
  'Denmark': ['Aalborg', 'Aarhus', 'Copenhagen', 'Esbjerg', 'Horsens', 'Kolding', 'Odense', 'Randers', 'Roskilde', 'Vejle'],
  'Dominican Republic': ['La Romana', 'La Vega', 'Puerto Plata', 'San Francisco de Macoris', 'San Pedro de Macoris', 'Santiago', 'Santo Domingo', 'Santo Domingo Este'],
  'Ecuador': ['Ambato', 'Cuenca', 'Duran', 'Esmeraldas', 'Guayaquil', 'Ibarra', 'Loja', 'Machala', 'Manta', 'Portoviejo', 'Quito', 'Santo Domingo'],
  'Egypt': ['Alexandria', 'Aswan', 'Asyut', 'Cairo', 'Damietta', 'Fayoum', 'Giza', 'Ismailia', 'Luxor', 'Mansoura', 'Port Said', 'Shubra El Kheima', 'Suez', 'Tanta', 'Zagazig'],
  'El Salvador': ['Apopa', 'Delgado', 'Mejicanos', 'San Miguel', 'San Salvador', 'Santa Ana', 'Santa Tecla', 'Soyapango'],
  'Estonia': ['Kohtla-Jarve', 'Maardu', 'Narva', 'Parnu', 'Rakvere', 'Tallinn', 'Tartu', 'Viljandi'],
  'Ethiopia': ['Adama', 'Addis Ababa', 'Awasa', 'Bahir Dar', 'Debre Markos', 'Dessie', 'Dire Dawa', 'Gondar', 'Jijiga', 'Jimma', 'Mekelle'],
  'Fiji': ['Ba', 'Labasa', 'Lautoka', 'Nadi', 'Savusavu', 'Sigatoka', 'Suva'],
  'Finland': ['Espoo', 'Helsinki', 'Joensuu', 'Jyvaskyla', 'Kouvola', 'Kuopio', 'Lahti', 'Oulu', 'Pori', 'Tampere', 'Turku', 'Vantaa'],
  'France': ['Angers', 'Bordeaux', 'Clermont-Ferrand', 'Dijon', 'Grenoble', 'Le Havre', 'Lille', 'Lyon', 'Marseille', 'Montpellier', 'Nantes', 'Nice', 'Nimes', 'Paris', 'Reims', 'Rennes', 'Saint-Etienne', 'Strasbourg', 'Toulon', 'Toulouse', 'Tours'],
  'Georgia': ['Batumi', 'Gori', 'Kutaisi', 'Poti', 'Rustavi', 'Samtredia', 'Tbilisi', 'Zugdidi'],
  'Germany': ['Augsburg', 'Berlin', 'Bielefeld', 'Bochum', 'Bonn', 'Bremen', 'Cologne', 'Dortmund', 'Dresden', 'Duisburg', 'Dusseldorf', 'Essen', 'Frankfurt', 'Hamburg', 'Hanover', 'Karlsruhe', 'Leipzig', 'Mannheim', 'Munich', 'Munster', 'Nuremberg', 'Stuttgart', 'Wiesbaden', 'Wuppertal'],
  'Ghana': ['Accra', 'Cape Coast', 'Koforidua', 'Kumasi', 'Obuasi', 'Sekondi-Takoradi', 'Sunyani', 'Takoradi', 'Tamale', 'Tema'],
  'Greece': ['Athens', 'Chania', 'Heraklion', 'Ioannina', 'Kalamata', 'Kavala', 'Larissa', 'Patras', 'Rhodes', 'Thessaloniki', 'Volos'],
  'Guatemala': ['Coban', 'Escuintla', 'Guatemala City', 'Huehuetenango', 'Mazatenango', 'Mixco', 'Quetzaltenango', 'Retalhuleu', 'Villa Nueva'],
  'Haiti': ['Cap-Haitien', 'Delmas', 'Gonaives', 'Jacmel', 'Jeremie', 'Les Cayes', 'Petionville', 'Port-au-Prince'],
  'Honduras': ['Catacamas', 'Choloma', 'Choluteca', 'Comayagua', 'Danli', 'El Progreso', 'La Ceiba', 'San Pedro Sula', 'Tegucigalpa'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Mong Kok', 'Sai Kung', 'Sha Tin', 'Tai Po', 'Tsuen Wan', 'Tuen Mun', 'Yuen Long'],
  'Hungary': ['Budapest', 'Debrecen', 'Eger', 'Gyor', 'Kecskemet', 'Miskolc', 'Nyiregyhaza', 'Pecs', 'Szeged', 'Szekesfehervar', 'Szombathely'],
  'Iceland': ['Akureyri', 'Gardabaer', 'Hafnarfjordur', 'Isafjordur', 'Kopavogur', 'Mosfellsbaer', 'Reykjavik', 'Selfoss'],
  'India': ['Agra', 'Ahmedabad', 'Allahabad', 'Amritsar', 'Bangalore', 'Bhopal', 'Chandigarh', 'Chennai', 'Coimbatore', 'Delhi', 'Guwahati', 'Hyderabad', 'Indore', 'Jabalpur', 'Jaipur', 'Jodhpur', 'Kanpur', 'Kochi', 'Kolkata', 'Lucknow', 'Madurai', 'Meerut', 'Mumbai', 'Mysore', 'Nagpur', 'Nashik', 'Patna', 'Pune', 'Rajkot', 'Ranchi', 'Surat', 'Thiruvananthapuram', 'Udaipur', 'Vadodara', 'Varanasi', 'Visakhapatnam'],
  'Indonesia': ['Ambon', 'Balikpapan', 'Banda Aceh', 'Bandar Lampung', 'Bandung', 'Banjarmasin', 'Batam', 'Bekasi', 'Bengkulu', 'Bogor', 'Cimahi', 'Cirebon', 'Denpasar', 'Depok', 'Gorontalo', 'Jakarta', 'Jambi', 'Jayapura', 'Kendari', 'Kupang', 'Lhokseumawe', 'Makassar', 'Malang', 'Mamuju', 'Manado', 'Mataram', 'Medan', 'Padang', 'Palembang', 'Palu', 'Pekanbaru', 'Pontianak', 'Samarinda', 'Semarang', 'Serang', 'Solo', 'Sorong', 'Sukabumi', 'Surabaya', 'Tangerang', 'Tanjung Pinang', 'Tarakan', 'Tasikmalaya', 'Ternate', 'Tidore', 'Yogyakarta'],
  'Iran': ['Ahvaz', 'Arak', 'Ardabil', 'Bandar Abbas', 'Hamadan', 'Isfahan', 'Karaj', 'Kerman', 'Kermanshah', 'Mashhad', 'Qom', 'Rasht', 'Shiraz', 'Tabriz', 'Tehran', 'Urmia', 'Yazd', 'Zahedan'],
  'Iraq': ['Amarah', 'Baghdad', 'Basra', 'Diwaniyah', 'Erbil', 'Fallujah', 'Hillah', 'Karbala', 'Kirkuk', 'Mosul', 'Najaf', 'Nasiriyah', 'Ramadi', 'Samawah', 'Sulaymaniyah'],
  'Ireland': ['Bray', 'Cork', 'Drogheda', 'Dublin', 'Dundalk', 'Ennis', 'Galway', 'Kilkenny', 'Limerick', 'Navan', 'Swords', 'Tralee', 'Waterford'],
  'Israel': ['Ashdod', 'Ashkelon', 'Bat Yam', 'Beersheba', 'Bnei Brak', 'Haifa', 'Holon', 'Jerusalem', 'Netanya', 'Petah Tikva', 'Ramat Gan', 'Rishon LeZion', 'Tel Aviv'],
  'Italy': ['Bologna', 'Brescia', 'Cagliari', 'Catania', 'Florence', 'Foggia', 'Genoa', 'Livorno', 'Messina', 'Milan', 'Modena', 'Naples', 'Padua', 'Palermo', 'Parma', 'Perugia', 'Prato', 'Reggio Calabria', 'Reggio Emilia', 'Rome', 'Taranto', 'Trieste', 'Turin', 'Venice', 'Verona'],
  'Jamaica': ['Kingston', 'Mandeville', 'May Pen', 'Montego Bay', 'Old Harbour', 'Portmore', 'Savanna-la-Mar', 'Spanish Town'],
  'Japan': ['Chiba', 'Fukuoka', 'Funabashi', 'Hachioji', 'Hamamatsu', 'Hiroshima', 'Kagoshima', 'Kawasaki', 'Kitakyushu', 'Kobe', 'Kumamoto', 'Kyoto', 'Matsuyama', 'Nagoya', 'Niigata', 'Okayama', 'Osaka', 'Sagamihara', 'Saitama', 'Sakai', 'Sapporo', 'Sendai', 'Shizuoka', 'Tokyo', 'Yokohama'],
  'Jordan': ['Amman', 'Aqaba', 'Irbid', 'Jerash', 'Karak', 'Madaba', 'Mafraq', 'Russeifa', 'Tafilah', 'Zarqa'],
  'Kazakhstan': ['Aktau', 'Aktobe', 'Almaty', 'Atyrau', 'Karaganda', 'Kostanay', 'Nur-Sultan', 'Oral', 'Pavlodar', 'Petropavlovsk', 'Semey', 'Shymkent', 'Taraz', 'Temirtau', 'Ust-Kamenogorsk'],
  'Kenya': ['Eldoret', 'Garissa', 'Kisumu', 'Kitale', 'Lamu', 'Machakos', 'Malindi', 'Meru', 'Mombasa', 'Nairobi', 'Nakuru', 'Nyeri', 'Thika'],
  'Kosovo': ['Ferizaj', 'Gjakova', 'Gjilan', 'Mitrovica', 'Peja', 'Podujevo', 'Pristina', 'Prizren'],
  'Kuwait': ['Ahmadi', 'Al Jahra', 'Farwaniya', 'Hawalli', 'Kuwait City', 'Mangaf', 'Sabah Al-Salem', 'Salmiya'],
  'Kyrgyzstan': ['Balykchy', 'Bishkek', 'Jalal-Abad', 'Karakol', 'Naryn', 'Osh', 'Tokmok', 'Uzgen'],
  'Laos': ['Luang Prabang', 'Pakse', 'Sam Neua', 'Savannakhet', 'Thakhek', 'Vang Vieng', 'Vientiane', 'Xam Nua'],
  'Latvia': ['Daugavpils', 'Jelgava', 'Jurmala', 'Liepaja', 'Ogre', 'Rezekne', 'Riga', 'Valmiera', 'Ventspils'],
  'Lebanon': ['Aley', 'Baalbek', 'Beirut', 'Byblos', 'Jounieh', 'Nabatieh', 'Sidon', 'Tripoli', 'Tyre', 'Zahle'],
  'Libya': ['Ajdabiya', 'Benghazi', 'Derna', 'Misrata', 'Sabha', 'Sirte', 'Tarhuna', 'Tripoli', 'Zawiya', 'Zliten'],
  'Lithuania': ['Alytus', 'Kaunas', 'Klaipeda', 'Marijampole', 'Mazeikiai', 'Panevezys', 'Siauliai', 'Telsiai', 'Utena', 'Vilnius'],
  'Luxembourg': ['Bettembourg', 'Diekirch', 'Differdange', 'Dudelange', 'Esch-sur-Alzette', 'Ettelbruck', 'Luxembourg City', 'Schifflange'],
  'Macau': ['Coloane', 'Cotai', 'Macau', 'Taipa'],
  'Madagascar': ['Antananarivo', 'Antsirabe', 'Antsiranana', 'Fianarantsoa', 'Mahajanga', 'Nosy Be', 'Toamasina', 'Toliara'],
  'Malaysia': ['Alor Setar', 'George Town', 'Ipoh', 'Johor Bahru', 'Klang', 'Kota Bharu', 'Kota Kinabalu', 'Kuala Lumpur', 'Kuala Terengganu', 'Kuantan', 'Kuching', 'Malaka', 'Miri', 'Petaling Jaya', 'Sandakan', 'Seremban', 'Shah Alam', 'Sibu', 'Taiping', 'Tawau'],
  'Maldives': ['Addu City', 'Eydhafushi', 'Fuvahmulah', 'Kulhudhuffushi', 'Male', 'Thinadhoo'],
  'Mali': ['Bamako', 'Gao', 'Kayes', 'Kidal', 'Koutiala', 'Mopti', 'Segou', 'Sikasso', 'Timbuktu'],
  'Malta': ['Birkirkara', 'Fgura', 'Mosta', 'Qormi', 'Rabat', 'San Gwann', 'Sliema', 'Valletta', 'Zabbar', 'Zejtun'],
  'Mexico': ['Acapulco', 'Aguascalientes', 'Cancun', 'Chihuahua', 'Guadalajara', 'Hermosillo', 'Juarez', 'Leon', 'Merida', 'Mexico City', 'Monterrey', 'Morelia', 'Oaxaca', 'Puebla', 'Queretaro', 'Saltillo', 'San Luis Potosi', 'Tijuana', 'Toluca', 'Tuxtla Gutierrez', 'Veracruz', 'Villahermosa', 'Zapopan'],
  'Moldova': ['Balti', 'Bender', 'Cahul', 'Chisinau', 'Orhei', 'Soroca', 'Tiraspol', 'Ungheni'],
  'Mongolia': ['Choibalsan', 'Darkhan', 'Erdenet', 'Hovd', 'Muren', 'Olgii', 'Ulaanbaatar'],
  'Montenegro': ['Bar', 'Bijelo Polje', 'Budva', 'Cetinje', 'Herceg Novi', 'Kotor', 'Niksic', 'Pljevlja', 'Podgorica', 'Ulcinj'],
  'Morocco': ['Agadir', 'Beni Mellal', 'Casablanca', 'El Jadida', 'Fes', 'Kenitra', 'Marrakech', 'Meknes', 'Mohammedia', 'Nador', 'Oujda', 'Rabat', 'Safi', 'Tangier', 'Tetouan'],
  'Mozambique': ['Beira', 'Chimoio', 'Lichinga', 'Maputo', 'Matola', 'Nacala', 'Nampula', 'Pemba', 'Quelimane', 'Tete'],
  'Myanmar': ['Bago', 'Mandalay', 'Mawlamyine', 'Meiktila', 'Monywa', 'Myingyan', 'Naypyidaw', 'Pathein', 'Sittwe', 'Taunggyi', 'Yangon'],
  'Nepal': ['Bhaktapur', 'Bharatpur', 'Biratnagar', 'Birgunj', 'Butwal', 'Dharan', 'Hetauda', 'Janakpur', 'Kathmandu', 'Lalitpur', 'Pokhara'],
  'Netherlands': ['Almere', 'Amersfoort', 'Amsterdam', 'Apeldoorn', 'Arnhem', 'Breda', 'Eindhoven', 'Enschede', 'Groningen', 'Haarlem', 'Leiden', 'Maastricht', 'Nijmegen', 'Rotterdam', 's-Hertogenbosch', 'The Hague', 'Tilburg', 'Utrecht', 'Zaanstad', 'Zwolle'],
  'New Zealand': ['Auckland', 'Christchurch', 'Dunedin', 'Hamilton', 'Invercargill', 'Napier', 'Napier-Hastings', 'Nelson', 'New Plymouth', 'Palmerston North', 'Rotorua', 'Tauranga', 'Wellington', 'Whangarei'],
  'Niger': ['Agadez', 'Arlit', 'Diffa', 'Dosso', 'Maradi', 'Niamey', 'Tahoua', 'Zinder'],
  'Nigeria': ['Aba', 'Abeokuta', 'Abuja', 'Ado-Ekiti', 'Akure', 'Benin City', 'Calabar', 'Enugu', 'Ibadan', 'Ilorin', 'Jos', 'Kaduna', 'Kano', 'Lagos', 'Maiduguri', 'Onitsha', 'Osogbo', 'Owerri', 'Oyo', 'Port Harcourt', 'Sokoto', 'Umuahia', 'Uyo', 'Warri', 'Zaria'],
  'North Macedonia': ['Bitola', 'Gostivar', 'Kumanovo', 'Ohrid', 'Prilep', 'Skopje', 'Strumica', 'Tetovo', 'Veles'],
  'Norway': ['Alesund', 'Bergen', 'Bodo', 'Drammen', 'Fredrikstad', 'Haugesund', 'Kristiansand', 'Oslo', 'Sandefjord', 'Sandnes', 'Sarpsborg', 'Skien', 'Stavanger', 'Tonsberg', 'Tromso', 'Trondheim'],
  'Oman': ['Barka', 'Ibri', 'Muscat', 'Nizwa', 'Rustaq', 'Saham', 'Salalah', 'Sohar', 'Sur'],
  'Pakistan': ['Bahawalpur', 'Dera Ghazi Khan', 'Dera Ismail Khan', 'Faisalabad', 'Gujranwala', 'Gujrat', 'Hyderabad', 'Islamabad', 'Jhang', 'Karachi', 'Kasur', 'Lahore', 'Larkana', 'Mardan', 'Multan', 'Peshawar', 'Quetta', 'Rahim Yar Khan', 'Rawalpindi', 'Sahiwal', 'Sargodha', 'Sheikhupura', 'Sialkot', 'Sukkur', 'Wah Cantonment'],
  'Palestine': ['Bethlehem', 'Deir al-Balah', 'Gaza', 'Hebron', 'Jenin', 'Jericho', 'Khan Yunis', 'Nablus', 'Qalqilya', 'Rafah', 'Ramallah', 'Tulkarm'],
  'Panama': ['Arraijan', 'Bocas del Toro', 'Chitre', 'Colon', 'David', 'La Chorrera', 'Panama City', 'San Miguelito', 'Santiago', 'Tocumen'],
  'Papua New Guinea': ['Bulolo', 'Goroka', 'Kimbe', 'Lae', 'Madang', 'Mount Hagen', 'Popondetta', 'Port Moresby', 'Wewak'],
  'Paraguay': ['Asuncion', 'Caaguazu', 'Capiata', 'Ciudad del Este', 'Concepcion', 'Encarnacion', 'Fernando de la Mora', 'Lambare', 'Luque', 'Mariano Roque Alonso', 'San Lorenzo'],
  'Peru': ['Arequipa', 'Ayacucho', 'Cajamarca', 'Chiclayo', 'Chimbote', 'Cusco', 'Huancayo', 'Huanuco', 'Ica', 'Iquitos', 'Juliaca', 'Lima', 'Piura', 'Pucallpa', 'Puno', 'Sullana', 'Tacna', 'Tarapoto', 'Trujillo', 'Tumbes'],
  'Philippines': ['Antipolo', 'Bacolod', 'Baguio', 'Butuan', 'Cagayan de Oro', 'Caloocan', 'Cebu City', 'Dasmariñas', 'Davao', 'General Santos', 'Iligan', 'Iloilo', 'Makati', 'Manila', 'Olongapo', 'Paranaque', 'Pasay', 'Pasig', 'Puerto Princesa', 'Quezon City', 'Tacloban', 'Taguig', 'Valenzuela', 'Zamboanga'],
  'Poland': ['Bialystok', 'Bydgoszcz', 'Czestochowa', 'Gdansk', 'Gliwice', 'Katowice', 'Kielce', 'Krakow', 'Lodz', 'Lublin', 'Olsztyn', 'Poznan', 'Radom', 'Rzeszow', 'Szczecin', 'Torun', 'Warsaw', 'Wroclaw', 'Zabrze'],
  'Portugal': ['Agualva-Cacem', 'Almada', 'Amadora', 'Aveiro', 'Braga', 'Coimbra', 'Evora', 'Faro', 'Funchal', 'Guimaraes', 'Leiria', 'Lisbon', 'Porto', 'Setubal', 'Vila Nova de Gaia', 'Viseu'],
  'Puerto Rico': ['Aguadilla', 'Arecibo', 'Bayamon', 'Caguas', 'Carolina', 'Guaynabo', 'Mayaguez', 'Ponce', 'San Juan', 'Toa Baja'],
  'Qatar': ['Al Daayen', 'Al Khor', 'Al Rayyan', 'Al Wakrah', 'Doha', 'Dukhan', 'Mesaieed', 'Umm Salal'],
  'Romania': ['Arad', 'Bacau', 'Baia Mare', 'Botosani', 'Braila', 'Brasov', 'Bucharest', 'Buzau', 'Cluj-Napoca', 'Constanta', 'Craiova', 'Galati', 'Iasi', 'Oradea', 'Pitesti', 'Ploiesti', 'Satu Mare', 'Sibiu', 'Targu Mures', 'Timisoara'],
  'Russia': ['Barnaul', 'Chelyabinsk', 'Irkutsk', 'Izhevsk', 'Kazan', 'Khabarovsk', 'Krasnodar', 'Krasnoyarsk', 'Moscow', 'Nizhny Novgorod', 'Novosibirsk', 'Perm', 'Rostov-on-Don', 'Saint Petersburg', 'Samara', 'Saratov', 'Tolyatti', 'Tyumen', 'Ufa', 'Ulyanovsk', 'Vladivostok', 'Volgograd', 'Voronezh', 'Yaroslavl', 'Yekaterinburg'],
  'Saudi Arabia': ['Abha', 'Al Khafj', 'Buraidah', 'Dammam', 'Hail', 'Jeddah', 'Jubail', 'Khamis Mushait', 'Khobar', 'Mecca', 'Medina', 'Najran', 'Riyadh', 'Tabuk', 'Taif', 'Yanbu'],
  'Senegal': ['Dakar', 'Diourbel', 'Kaolack', 'Mbour', 'Rufisque', 'Saint-Louis', 'Thies', 'Touba', 'Ziguinchor'],
  'Serbia': ['Belgrade', 'Cacak', 'Kragujevac', 'Kraljevo', 'Leskovac', 'Nis', 'Novi Pazar', 'Novi Sad', 'Pancevo', 'Smederevo', 'Subotica', 'Uzice', 'Vranje', 'Zrenjanin'],
  'Singapore': ['Ang Mo Kio', 'Bedok', 'Bukit Merah', 'Clementi', 'Hougang', 'Jurong', 'Sengkang', 'Singapore', 'Tampines', 'Toa Payoh', 'Woodlands', 'Yishun'],
  'Slovakia': ['Banska Bystrica', 'Bratislava', 'Kosice', 'Martin', 'Nitra', 'Poprad', 'Presov', 'Trencin', 'Trnava', 'Zilina'],
  'Slovenia': ['Celje', 'Kamnik', 'Koper', 'Kranj', 'Ljubljana', 'Maribor', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Velenje'],
  'Somalia': ['Baidoa', 'Beledweyne', 'Berbera', 'Bosaso', 'Galkayo', 'Garowe', 'Hargeisa', 'Kismayo', 'Merca', 'Mogadishu'],
  'South Africa': ['Benoni', 'Bloemfontein', 'Cape Town', 'Centurion', 'Durban', 'East London', 'George', 'Johannesburg', 'Kimberley', 'Nelspruit', 'Pietermaritzburg', 'Polokwane', 'Port Elizabeth', 'Pretoria', 'Rustenburg', 'Soweto', 'Stellenbosch', 'Tembisa', 'Vereeniging'],
  'South Korea': ['Ansan', 'Anyang', 'Bucheon', 'Busan', 'Changwon', 'Cheonan', 'Cheongju', 'Daegu', 'Daejeon', 'Goyang', 'Gwangju', 'Incheon', 'Jeju', 'Jeonju', 'Pohang', 'Seongnam', 'Seoul', 'Suwon', 'Ulsan', 'Yongin'],
  'Spain': ['A Coruna', 'Alicante', 'Almeria', 'Barcelona', 'Bilbao', 'Cartagena', 'Cordoba', 'Elche', 'Gijon', 'Granada', 'Huelva', 'Jerez de la Frontera', 'Leon', 'Madrid', 'Malaga', 'Murcia', 'Oviedo', 'Palma', 'Pamplona', 'Salamanca', 'Santa Cruz de Tenerife', 'Seville', 'Valencia', 'Valladolid', 'Vigo', 'Vitoria-Gasteiz', 'Zaragoza'],
  'Sri Lanka': ['Anuradhapura', 'Badulla', 'Batticaloa', 'Colombo', 'Galle', 'Jaffna', 'Kandy', 'Kurunegala', 'Matara', 'Negombo', 'Ratnapura', 'Trincomalee'],
  'Sudan': ['El Fasher', 'El Obeid', 'Gedaref', 'Kassala', 'Khartoum', 'Khartoum North', 'Kosti', 'Nyala', 'Omdurman', 'Port Sudan', 'Wad Madani'],
  'Sweden': ['Boras', 'Eskilstuna', 'Gavle', 'Gothenburg', 'Halmstad', 'Helsingborg', 'Jonkoping', 'Karlstad', 'Linkoping', 'Lund', 'Malmo', 'Norrkoping', 'Orebro', 'Sodertalje', 'Stockholm', 'Umea', 'Uppsala', 'Vasteras', 'Vaxjo'],
  'Switzerland': ['Basel', 'Bern', 'Biel', 'Chur', 'Fribourg', 'Geneva', 'Lausanne', 'Lucerne', 'Lugano', 'Neuchatel', 'Schaffhausen', 'Sion', 'St. Gallen', 'Thun', 'Uster', 'Winterthur', 'Zurich'],
  'Syria': ['Aleppo', 'Damascus', 'Daraa', 'Deir ez-Zor', 'Hama', 'Hasakeh', 'Homs', 'Idlib', 'Latakia', 'Raqqa', 'Tartus'],
  'Taiwan': ['Changhua', 'Chiayi', 'Hsinchu', 'Hualien', 'Kaohsiung', 'Keelung', 'Miaoli', 'Nantou', 'Pingtung', 'Taichung', 'Tainan', 'Taipei', 'Taitung', 'Taoyuan', 'Yilan', 'Yunlin'],
  'Tajikistan': ['Bokhtar', 'Dushanbe', 'Isfara', 'Istaravshan', 'Khujand', 'Konibodom', 'Kulob', 'Tursunzoda'],
  'Tanzania': ['Arusha', 'Bukoba', 'Dar es Salaam', 'Dodoma', 'Iringa', 'Kigoma', 'Mbeya', 'Morogoro', 'Moshi', 'Mwanza', 'Songea', 'Tabora', 'Tanga', 'Tunduma', 'Zanzibar City'],
  'Thailand': ['Ayutthaya', 'Bangkok', 'Chiang Mai', 'Chiang Rai', 'Hat Yai', 'Kanchanaburi', 'Khon Kaen', 'Lampang', 'Nakhon Ratchasima', 'Nakhon Si Thammarat', 'Nonthaburi', 'Pak Kret', 'Pattaya', 'Phitsanulok', 'Phuket', 'Rayong', 'Songkhla', 'Surat Thani', 'Ubon Ratchathani', 'Udon Thani'],
  'Timor-Leste': ['Ainaro', 'Baucau', 'Dili', 'Ermera', 'Lospalos', 'Maliana', 'Suai'],
  'Tunisia': ['Ariana', 'Ben Arous', 'Bizerte', 'Ettadhamen', 'Gabes', 'Gafsa', 'Houmt Souk', 'Kairouan', 'Kasserine', 'M\'saken', 'Monastir', 'Sfax', 'Sousse', 'Tunis'],
  'Turkey': ['Adana', 'Aksaray', 'Ankara', 'Antalya', 'Aydin', 'Balikesir', 'Batman', 'Bursa', 'Denizli', 'Diyarbakir', 'Edirne', 'Elazig', 'Erzurum', 'Eskisehir', 'Gaziantep', 'Isparta', 'Istanbul', 'Izmir', 'Kahramanmaras', 'Kayseri', 'Konya', 'Malatya', 'Manisa', 'Mersin', 'Samsun', 'Sanliurfa', 'Sivas', 'Tekirdag', 'Trabzon', 'Van'],
  'Turkmenistan': ['Ashgabat', 'Balkanabat', 'Bayramaly', 'Dashoguz', 'Mary', 'Turkmenabat', 'Turkmenbashi'],
  'Uganda': ['Arua', 'Entebbe', 'Fort Portal', 'Gulu', 'Hoima', 'Jinja', 'Kabale', 'Kampala', 'Lira', 'Masaka', 'Mbale', 'Mbarara', 'Mukono', 'Soroti'],
  'Ukraine': ['Chernihiv', 'Chernivtsi', 'Dnipro', 'Donetsk', 'Ivano-Frankivsk', 'Kharkiv', 'Khmelnytskyi', 'Kremenchuk', 'Kropyvnytskyi', 'Kyiv', 'Luhansk', 'Lutsk', 'Lviv', 'Mariupol', 'Mykolaiv', 'Odessa', 'Poltava', 'Rivne', 'Sumy', 'Ternopil', 'Uzhhorod', 'Vinnytsia', 'Zaporizhzhia', 'Zhytomyr'],
  'United Arab Emirates': ['Abu Dhabi', 'Ajman', 'Al Ain', 'Dubai', 'Fujairah', 'Khor Fakkan', 'Ras Al Khaimah', 'Sharjah', 'Umm Al Quwain'],
  'United Kingdom': ['Aberdeen', 'Belfast', 'Birmingham', 'Bradford', 'Brighton', 'Bristol', 'Cambridge', 'Cardiff', 'Coventry', 'Derby', 'Dundee', 'Edinburgh', 'Glasgow', 'Hull', 'Leeds', 'Leicester', 'Liverpool', 'London', 'Manchester', 'Milton Keynes', 'Newcastle', 'Nottingham', 'Oxford', 'Plymouth', 'Portsmouth', 'Reading', 'Sheffield', 'Southampton', 'Stoke-on-Trent', 'Swansea', 'Wolverhampton'],
  'United States': ['Albuquerque', 'Anchorage', 'Atlanta', 'Austin', 'Baltimore', 'Boise', 'Boston', 'Charleston', 'Charlotte', 'Chicago', 'Cincinnati', 'Cleveland', 'Columbus', 'Dallas', 'Denver', 'Detroit', 'El Paso', 'Fresno', 'Hartford', 'Honolulu', 'Houston', 'Indianapolis', 'Jacksonville', 'Kansas City', 'Las Vegas', 'Long Beach', 'Los Angeles', 'Madison', 'Memphis', 'Mesa', 'Miami', 'Milwaukee', 'Minneapolis', 'Nashville', 'New Orleans', 'New York', 'Oakland', 'Omaha', 'Omaha', 'Orlando', 'Philadelphia', 'Phoenix', 'Pittsburgh', 'Portland', 'Raleigh', 'Richmond', 'Sacramento', 'Salt Lake City', 'San Antonio', 'San Diego', 'San Francisco', 'San Jose', 'Savannah', 'Seattle', 'St. Louis', 'Tampa', 'Tucson', 'Tucson', 'Tulsa', 'Washington'],
  'Uruguay': ['Artigas', 'Ciudad de la Costa', 'Las Piedras', 'Maldonado', 'Melo', 'Minas', 'Montevideo', 'Paysandu', 'Rivera', 'Salto', 'Tacuarembo'],
  'Uzbekistan': ['Andijan', 'Bukhara', 'Fergana', 'Gulistan', 'Jizzakh', 'Karakalpakstan', 'Kokand', 'Margilan', 'Namangan', 'Navoiy', 'Nukus', 'Samarkand', 'Tashkent', 'Termez', 'Urgench'],
  'Venezuela': ['Barcelona', 'Barquisimeto', 'Caracas', 'Ciudad Bolivar', 'Ciudad Guayana', 'Cumana', 'Guarenas', 'Los Teques', 'Maracaibo', 'Maracay', 'Maturin', 'Merida', 'Puerto La Cruz', 'San Cristobal', 'Valencia'],
  'Vietnam': ['Bac Ninh', 'Bien Hoa', 'Buon Ma Thuot', 'Can Tho', 'Da Lat', 'Da Nang', 'Ha Long', 'Hai Phong', 'Hanoi', 'Ho Chi Minh City', 'Hue', 'Long Xuyen', 'My Tho', 'Nam Dinh', 'Nha Trang', 'Quy Nhon', 'Rach Gia', 'Thai Nguyen', 'Vinh', 'Vung Tau'],
  'Yemen': ['Aden', 'Al Mukalla', 'Amran', 'Dhamar', 'Hodeidah', 'Ibb', 'Sanaa', 'Sayyan', 'Taiz', 'Zinjibar'],
  'Zimbabwe': ['Bulawayo', 'Chitungwiza', 'Epworth', 'Gweru', 'Harare', 'Kadoma', 'Kwekwe', 'Masvingo', 'Mutare', 'Victoria Falls'],
};
/// 250 negara lengkap untuk filter online users
const List<String> allCountries = [
  'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus',
  'Belgium', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada', 'Chile',
  'China', 'Colombia', 'Costa Rica', 'Cote d\'Ivoire', 'Croatia', 'Cuba',
  'Cyprus', 'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt',
  'El Salvador', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France',
  'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Haiti',
  'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
  'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait',
  'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Libya', 'Lithuania',
  'Luxembourg', 'Macau', 'Madagascar', 'Malaysia', 'Maldives', 'Mali',
  'Malta', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco',
  'Mozambique', 'Myanmar', 'Nepal', 'Netherlands', 'New Zealand', 'Niger',
  'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palestine',
  'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
  'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
  'Senegal', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia',
  'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden',
  'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
  'Timor-Leste', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine',
  'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
  'Venezuela', 'Vietnam', 'Yemen', 'Zimbabwe',
];

/// Mendapatkan list kota untuk negara tertentu
List<String> getCitiesForCountry(String country) =>
    kotaByNegara[country] ?? [];

/// Mendapatkan nama negara (kompatibilitas dengan entry_screen)
String negaraLabel(String key, bool isId) => key;

/// Mendapatkan list negara yang punya data kota
List<String> getNegaraKeys() => kotaByNegara.keys.toList();
