// Daftar negara dan kota lengkap
// Data dikurasi dari sumber publik

const Map<String, List<String>> kotaByNegara = {
  'Afghanistan': ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz', 'Ghazni', 'Lashkar Gah'],
  'Albania': ['Tirana', 'Durres', 'Vlore', 'Shkoder', 'Elbasan', 'Fier', 'Korce', 'Berat'],
  'Algeria': ['Algiers', 'Oran', 'Constantine', 'Annaba', 'Blida', 'Batna', 'Setif', 'Djelfa', 'Sidi Bel Abbes'],
  'Angola': ['Luanda', 'Huambo', 'Lobito', 'Benguela', 'Namibe', 'Lubango', 'Cabinda'],
  'Argentina': ['Buenos Aires', 'Cordoba', 'Rosario', 'Mendoza', 'La Plata', 'San Miguel de Tucuman', 'Mar del Plata', 'Salta', 'Santa Fe', 'San Juan', 'Resistencia', 'Santiago del Estero', 'Corrientes', 'Posadas'],
  'Armenia': ['Yerevan', 'Gyumri', 'Vanadzor', 'Vagharshapat', 'Abovyan', 'Kapan'],
  'Australia': ['Sydney', 'Melbourne', 'Brisbane', 'Perth', 'Adelaide', 'Canberra', 'Darwin', 'Hobart', 'Gold Coast', 'Newcastle', 'Wollongong', 'Geelong', 'Townsville', 'Cairns', 'Toowoomba'],
  'Austria': ['Vienna', 'Graz', 'Linz', 'Salzburg', 'Innsbruck', 'Klagenfurt', 'Villach', 'Wels', 'Sankt Polten', 'Dornbirn'],
  'Azerbaijan': ['Baku', 'Ganja', 'Sumqayit', 'Mingachevir', 'Lankaran', 'Shirvan', 'Nakhchivan'],
  'Bahrain': ['Manama', 'Riffa', 'Muharraq', 'Hamad Town', 'Aali', 'Isa Town', 'Sitra'],
  'Bangladesh': ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Comilla', 'Rangpur', 'Bogra', 'Barisal', 'Cox\'s Bazar'],
  'Belarus': ['Minsk', 'Gomel', 'Vitebsk', 'Mogilev', 'Grodno', 'Brest', 'Babruysk', 'Baranovichi'],
  'Belgium': ['Brussels', 'Antwerp', 'Ghent', 'Bruges', 'Liege', 'Namur', 'Leuven', 'Mons', 'Aalst', 'Kortrijk'],
  'Bhutan': ['Thimphu', 'Phuntsholing', 'Paro', 'Gelephu', 'Samdrup Jongkhar'],
  'Bolivia': ['Santa Cruz', 'La Paz', 'Cochabamba', 'Oruro', 'Sucre', 'Tarija', 'Potosi', 'Sacaba', 'Quillacollo'],
  'Bosnia and Herzegovina': ['Sarajevo', 'Banja Luka', 'Tuzla', 'Zenica', 'Mostar', 'Bijeljina', 'Brcko', 'Trebinje'],
  'Brazil': ['Sao Paulo', 'Rio de Janeiro', 'Brasilia', 'Salvador', 'Fortaleza', 'Belo Horizonte', 'Manaus', 'Curitiba', 'Recife', 'Porto Alegre', 'Belem', 'Goiania', 'Guarulhos', 'Campinas', 'Sao Luis', 'Maceio', 'Campo Grande', 'Teresina', 'Joao Pessoa', 'Natal', 'Aracaju', 'Florianopolis', 'Uberlandia', 'Sorocaba'],
  'Brunei': ['Bandar Seri Begawan', 'Kuala Belait', 'Seria', 'Tutong', 'Temburong'],
  'Bulgaria': ['Sofia', 'Plovdiv', 'Varna', 'Burgas', 'Rousse', 'Stara Zagora', 'Pleven', 'Sliven', 'Dobrich', 'Shumen'],
  'Burkina Faso': ['Ouagadougou', 'Bobo-Dioulasso', 'Koudougou', 'Banfora', 'Ouahigouya', 'Dedougou'],
  'Cambodia': ['Phnom Penh', 'Siem Reap', 'Battambang', 'Sihanoukville', 'Kampong Cham', 'Poipet', 'Kampot', 'Kampong Chhnang'],
  'Cameroon': ['Yaounde', 'Douala', 'Garoua', 'Bamenda', 'Bafoussam', 'Maroua', 'Ngaoundere', 'Kumba', 'Ebolowa'],
  'Canada': ['Toronto', 'Montreal', 'Vancouver', 'Calgary', 'Edmonton', 'Ottawa', 'Winnipeg', 'Quebec City', 'Hamilton', 'Brampton', 'Surrey', 'Halifax', 'London', 'Markham', 'Vaughan', 'Gatineau', 'Saskatoon', 'Regina', 'Burnaby', 'Kitchener', 'Victoria', 'Windsor'],
  'Chile': ['Santiago', 'Valparaiso', 'Concepcion', 'La Serena', 'Antofagasta', 'Temuco', 'Rancagua', 'Talca', 'Arica', 'Chillan', 'Iquique', 'Osorno'],
  'China': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Chengdu', 'Hangzhou', 'Wuhan', 'Xi\'an', 'Nanjing', 'Tianjin', 'Chongqing', 'Dongguan', 'Foshan', 'Shenyang', 'Harbin', 'Dalian', 'Jinan', 'Qingdao', 'Zhengzhou', 'Changsha', 'Kunming', 'Xiamen', 'Hefei', 'Fuzhou', 'Nanning', 'Guiyang', 'Urumqi', 'Lanzhou', 'Hohhot'],
  'Colombia': ['Bogota', 'Medellin', 'Cali', 'Barranquilla', 'Cartagena', 'Cucuta', 'Bucaramanga', 'Pereira', 'Santa Marta', 'Ibague', 'Pasto', 'Manizales', 'Neiva', 'Villavicencio', 'Armenia'],
  'Costa Rica': ['San Jose', 'Alajuela', 'Desamparados', 'Cartago', 'Heredia', 'Limon', 'Liberia', 'Puntarenas'],
  'Cote d\'Ivoire': ['Abidjan', 'Bouake', 'Daloa', 'Yamoussoukro', 'San-Pedro', 'Korhogo', 'Man', 'Divo', 'Gagnoa'],
  'Croatia': ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Dubrovnik', 'Slavonski Brod', 'Karlovac', 'Varazdin', 'Sibenik'],
  'Cuba': ['Havana', 'Santiago de Cuba', 'Holguin', 'Camaguey', 'Santa Clara', 'Guantanamo', 'Bayamo', 'Las Tunas', 'Cienfuegos', 'Pinar del Rio'],
  'Cyprus': ['Nicosia', 'Limassol', 'Larnaca', 'Paphos', 'Famagusta', 'Kyrenia', 'Paralimni'],
  'Czech Republic': ['Prague', 'Brno', 'Ostrava', 'Plzen', 'Liberec', 'Olomouc', 'Ceske Budejovice', 'Hradec Kralove', 'Pardubice', 'Usti nad Labem'],
  'Denmark': ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens', 'Vejle', 'Roskilde'],
  'Dominican Republic': ['Santo Domingo', 'Santiago', 'Santo Domingo Este', 'La Romana', 'San Pedro de Macoris', 'San Francisco de Macoris', 'Puerto Plata', 'La Vega'],
  'Ecuador': ['Guayaquil', 'Quito', 'Cuenca', 'Santo Domingo', 'Machala', 'Duran', 'Ambato', 'Portoviejo', 'Manta', 'Loja', 'Ibarra', 'Esmeraldas'],
  'Egypt': ['Cairo', 'Alexandria', 'Giza', 'Shubra El Kheima', 'Port Said', 'Suez', 'Luxor', 'Mansoura', 'Aswan', 'Tanta', 'Ismailia', 'Asyut', 'Zagazig', 'Damietta', 'Fayoum'],
  'El Salvador': ['San Salvador', 'Santa Ana', 'San Miguel', 'Mejicanos', 'Soyapango', 'Apopa', 'Santa Tecla', 'Delgado'],
  'Estonia': ['Tallinn', 'Tartu', 'Narva', 'Parnu', 'Kohtla-Jarve', 'Viljandi', 'Rakvere', 'Maardu'],
  'Ethiopia': ['Addis Ababa', 'Dire Dawa', 'Mekelle', 'Gondar', 'Awasa', 'Bahir Dar', 'Dessie', 'Jimma', 'Jijiga', 'Adama', 'Debre Markos'],
  'Fiji': ['Suva', 'Lautoka', 'Nadi', 'Labasa', 'Ba', 'Sigatoka', 'Savusavu'],
  'Finland': ['Helsinki', 'Espoo', 'Tampere', 'Vantaa', 'Oulu', 'Turku', 'Jyvaskyla', 'Lahti', 'Kuopio', 'Kouvola', 'Pori', 'Joensuu'],
  'France': ['Paris', 'Marseille', 'Lyon', 'Toulouse', 'Nice', 'Nantes', 'Strasbourg', 'Montpellier', 'Bordeaux', 'Lille', 'Rennes', 'Reims', 'Saint-Etienne', 'Le Havre', 'Toulon', 'Grenoble', 'Dijon', 'Angers', 'Nimes', 'Clermont-Ferrand', 'Tours'],
  'Georgia': ['Tbilisi', 'Kutaisi', 'Batumi', 'Rustavi', 'Zugdidi', 'Gori', 'Poti', 'Samtredia'],
  'Germany': ['Berlin', 'Hamburg', 'Munich', 'Cologne', 'Frankfurt', 'Stuttgart', 'Dusseldorf', 'Leipzig', 'Dortmund', 'Essen', 'Bremen', 'Dresden', 'Hanover', 'Nuremberg', 'Duisburg', 'Bochum', 'Wuppertal', 'Bielefeld', 'Bonn', 'Mannheim', 'Karlsruhe', 'Augsburg', 'Wiesbaden', 'Munster'],
  'Ghana': ['Accra', 'Kumasi', 'Tamale', 'Sekondi-Takoradi', 'Tema', 'Obuasi', 'Takoradi', 'Cape Coast', 'Koforidua', 'Sunyani'],
  'Greece': ['Athens', 'Thessaloniki', 'Patras', 'Heraklion', 'Larissa', 'Volos', 'Rhodes', 'Ioannina', 'Chania', 'Kavala', 'Kalamata'],
  'Guatemala': ['Guatemala City', 'Mixco', 'Villa Nueva', 'Quetzaltenango', 'Escuintla', 'Mazatenango', 'Huehuetenango', 'Coban', 'Retalhuleu'],
  'Haiti': ['Port-au-Prince', 'Cap-Haitien', 'Delmas', 'Petionville', 'Gonaives', 'Les Cayes', 'Jacmel', 'Jeremie'],
  'Honduras': ['Tegucigalpa', 'San Pedro Sula', 'Choloma', 'La Ceiba', 'El Progreso', 'Comayagua', 'Choluteca', 'Catacamas', 'Danli'],
  'Hong Kong': ['Hong Kong', 'Kowloon', 'Mong Kok', 'Tsuen Wan', 'Sha Tin', 'Tuen Mun', 'Yuen Long', 'Tai Po', 'Sai Kung'],
  'Hungary': ['Budapest', 'Debrecen', 'Miskolc', 'Szeged', 'Pecs', 'Gyor', 'Nyiregyhaza', 'Kecskemet', 'Szekesfehervar', 'Szombathely', 'Eger'],
  'Iceland': ['Reykjavik', 'Kopavogur', 'Hafnarfjordur', 'Akureyri', 'Gardabaer', 'Mosfellsbaer', 'Selfoss', 'Isafjordur'],
  'India': ['Mumbai', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Pune', 'Ahmedabad', 'Jaipur', 'Surat', 'Lucknow', 'Kanpur', 'Nagpur', 'Indore', 'Bhopal', 'Patna', 'Vadodara', 'Visakhapatnam', 'Coimbatore', 'Kochi', 'Agra', 'Varanasi', 'Madurai', 'Meerut', 'Nashik', 'Rajkot', 'Amritsar', 'Jodhpur', 'Ranchi', 'Guwahati', 'Chandigarh', 'Mysore', 'Thiruvananthapuram', 'Jabalpur', 'Allahabad', 'Udaipur'],
  'Indonesia': ['Jakarta', 'Surabaya', 'Bandung', 'Medan', 'Semarang', 'Makassar', 'Yogyakarta', 'Palembang', 'Denpasar', 'Tangerang', 'Depok', 'Bekasi', 'Bogor', 'Batam', 'Pekanbaru', 'Malang', 'Padang', 'Manado', 'Samarinda', 'Balikpapan', 'Banjarmasin', 'Pontianak', 'Mataram', 'Kupang', 'Ambon', 'Jayapura', 'Solo', 'Cirebon', 'Tasikmalaya', 'Sukabumi', 'Serang', 'Bengkulu', 'Jambi', 'Tanjung Pinang', 'Bandar Lampung', 'Gorontalo', 'Kendari', 'Palu', 'Tarakan', 'Banda Aceh', 'Lhokseumawe', 'Ternate', 'Sorong', 'Mamuju', 'Tidore'],
  'Iran': ['Tehran', 'Mashhad', 'Isfahan', 'Karaj', 'Tabriz', 'Shiraz', 'Ahvaz', 'Qom', 'Kermanshah', 'Rasht', 'Zahedan', 'Kerman', 'Yazd', 'Arak', 'Ardabil', 'Bandar Abbas', 'Hamadan', 'Urmia'],
  'Iraq': ['Baghdad', 'Basra', 'Mosul', 'Erbil', 'Kirkuk', 'Najaf', 'Sulaymaniyah', 'Karbala', 'Nasiriyah', 'Amarah', 'Diwaniyah', 'Hillah', 'Fallujah', 'Ramadi', 'Samawah'],
  'Ireland': ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Swords', 'Bray', 'Navan', 'Ennis', 'Kilkenny', 'Tralee'],
  'Israel': ['Jerusalem', 'Tel Aviv', 'Haifa', 'Rishon LeZion', 'Petah Tikva', 'Ashdod', 'Netanya', 'Beersheba', 'Holon', 'Bnei Brak', 'Ramat Gan', 'Bat Yam', 'Ashkelon'],
  'Italy': ['Rome', 'Milan', 'Naples', 'Turin', 'Palermo', 'Genoa', 'Bologna', 'Florence', 'Catania', 'Venice', 'Verona', 'Messina', 'Padua', 'Trieste', 'Brescia', 'Parma', 'Taranto', 'Prato', 'Modena', 'Reggio Calabria', 'Reggio Emilia', 'Perugia', 'Livorno', 'Cagliari', 'Foggia'],
  'Jamaica': ['Kingston', 'Spanish Town', 'Montego Bay', 'Portmore', 'May Pen', 'Mandeville', 'Old Harbour', 'Savanna-la-Mar'],
  'Japan': ['Tokyo', 'Osaka', 'Kyoto', 'Sapporo', 'Nagoya', 'Fukuoka', 'Hiroshima', 'Yokohama', 'Kobe', 'Sendai', 'Kawasaki', 'Saitama', 'Chiba', 'Kitakyushu', 'Sakai', 'Niigata', 'Hamamatsu', 'Shizuoka', 'Sagamihara', 'Okayama', 'Kumamoto', 'Kagoshima', 'Funabashi', 'Hachioji', 'Matsuyama'],
  'Jordan': ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Russeifa', 'Mafraq', 'Jerash', 'Madaba', 'Karak', 'Tafilah'],
  'Kazakhstan': ['Almaty', 'Nur-Sultan', 'Shymkent', 'Karaganda', 'Aktobe', 'Taraz', 'Pavlodar', 'Ust-Kamenogorsk', 'Semey', 'Atyrau', 'Kostanay', 'Petropavlovsk', 'Oral', 'Temirtau', 'Aktau'],
  'Kenya': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Nyeri', 'Machakos', 'Meru', 'Kitale', 'Garissa', 'Lamu'],
  'Kosovo': ['Pristina', 'Prizren', 'Peja', 'Gjakova', 'Gjilan', 'Ferizaj', 'Podujevo', 'Mitrovica'],
  'Kuwait': ['Kuwait City', 'Hawalli', 'Salmiya', 'Ahmadi', 'Sabah Al-Salem', 'Al Jahra', 'Farwaniya', 'Mangaf'],
  'Kyrgyzstan': ['Bishkek', 'Osh', 'Jalal-Abad', 'Karakol', 'Tokmok', 'Balykchy', 'Uzgen', 'Naryn'],
  'Laos': ['Vientiane', 'Luang Prabang', 'Pakse', 'Savannakhet', 'Thakhek', 'Sam Neua', 'Xam Nua', 'Vang Vieng'],
  'Latvia': ['Riga', 'Daugavpils', 'Liepaja', 'Jelgava', 'Jurmala', 'Ventspils', 'Rezekne', 'Ogre', 'Valmiera'],
  'Lebanon': ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh', 'Zahle', 'Byblos', 'Baalbek', 'Aley', 'Nabatieh'],
  'Libya': ['Tripoli', 'Benghazi', 'Misrata', 'Tarhuna', 'Sirte', 'Zawiya', 'Zliten', 'Ajdabiya', 'Derna', 'Sabha'],
  'Lithuania': ['Vilnius', 'Kaunas', 'Klaipeda', 'Siauliai', 'Panevezys', 'Alytus', 'Marijampole', 'Mazeikiai', 'Utena', 'Telsiai'],
  'Luxembourg': ['Luxembourg City', 'Esch-sur-Alzette', 'Differdange', 'Dudelange', 'Bettembourg', 'Schifflange', 'Ettelbruck', 'Diekirch'],
  'Macau': ['Macau', 'Taipa', 'Coloane', 'Cotai'],
  'Madagascar': ['Antananarivo', 'Toamasina', 'Antsirabe', 'Mahajanga', 'Fianarantsoa', 'Toliara', 'Antsiranana', 'Nosy Be'],
  'Malaysia': ['Kuala Lumpur', 'George Town', 'Johor Bahru', 'Ipoh', 'Malaka', 'Kota Kinabalu', 'Kuching', 'Shah Alam', 'Petaling Jaya', 'Klang', 'Kuantan', 'Alor Setar', 'Miri', 'Sandakan', 'Tawau', 'Seremban', 'Kota Bharu', 'Kuala Terengganu', 'Sibu', 'Taiping'],
  'Maldives': ['Male', 'Addu City', 'Fuvahmulah', 'Kulhudhuffushi', 'Thinadhoo', 'Eydhafushi'],
  'Mali': ['Bamako', 'Sikasso', 'Mopti', 'Koutiala', 'Segou', 'Kayes', 'Gao', 'Timbuktu', 'Kidal'],
  'Malta': ['Valletta', 'Birkirkara', 'Mosta', 'Qormi', 'Zabbar', 'Sliema', 'San Gwann', 'Rabat', 'Fgura', 'Zejtun'],
  'Mexico': ['Mexico City', 'Guadalajara', 'Monterrey', 'Puebla', 'Tijuana', 'Leon', 'Juarez', 'Zapopan', 'Merida', 'Cancun', 'Acapulco', 'Queretaro', 'Chihuahua', 'San Luis Potosi', 'Aguascalientes', 'Hermosillo', 'Saltillo', 'Morelia', 'Veracruz', 'Villahermosa', 'Toluca', 'Oaxaca', 'Tuxtla Gutierrez'],
  'Moldova': ['Chisinau', 'Tiraspol', 'Balti', 'Bender', 'Cahul', 'Ungheni', 'Soroca', 'Orhei'],
  'Mongolia': ['Ulaanbaatar', 'Darkhan', 'Erdenet', 'Choibalsan', 'Muren', 'Olgii', 'Hovd'],
  'Montenegro': ['Podgorica', 'Niksic', 'Pljevlja', 'Bijelo Polje', 'Cetinje', 'Bar', 'Herceg Novi', 'Ulcinj', 'Budva', 'Kotor'],
  'Morocco': ['Casablanca', 'Rabat', 'Fes', 'Marrakech', 'Agadir', 'Tangier', 'Meknes', 'Oujda', 'Kenitra', 'Tetouan', 'Nador', 'Safi', 'Mohammedia', 'El Jadida', 'Beni Mellal'],
  'Mozambique': ['Maputo', 'Matola', 'Beira', 'Nampula', 'Chimoio', 'Nacala', 'Quelimane', 'Tete', 'Lichinga', 'Pemba'],
  'Myanmar': ['Yangon', 'Mandalay', 'Naypyidaw', 'Bago', 'Mawlamyine', 'Taunggyi', 'Meiktila', 'Sittwe', 'Myingyan', 'Pathein', 'Monywa'],
  'Nepal': ['Kathmandu', 'Pokhara', 'Lalitpur', 'Biratnagar', 'Birgunj', 'Bharatpur', 'Butwal', 'Dharan', 'Hetauda', 'Bhaktapur', 'Janakpur'],
  'Netherlands': ['Amsterdam', 'Rotterdam', 'The Hague', 'Utrecht', 'Eindhoven', 'Tilburg', 'Groningen', 'Almere', 'Breda', 'Nijmegen', 'Arnhem', 'Haarlem', 'Enschede', 'Amersfoort', 'Zaanstad', 'Apeldoorn', 's-Hertogenbosch', 'Zwolle', 'Maastricht', 'Leiden'],
  'New Zealand': ['Auckland', 'Wellington', 'Christchurch', 'Hamilton', 'Tauranga', 'Napier', 'Dunedin', 'Palmerston North', 'Nelson', 'Rotorua', 'New Plymouth', 'Whangarei', 'Invercargill', 'Napier-Hastings'],
  'Niger': ['Niamey', 'Zinder', 'Maradi', 'Tahoua', 'Agadez', 'Dosso', 'Diffa', 'Arlit'],
  'Nigeria': ['Lagos', 'Kano', 'Ibadan', 'Abuja', 'Port Harcourt', 'Benin City', 'Maiduguri', 'Zaria', 'Aba', 'Kaduna', 'Enugu', 'Abeokuta', 'Jos', 'Ilorin', 'Oyo', 'Warri', 'Sokoto', 'Calabar', 'Owerri', 'Akure', 'Osogbo', 'Uyo', 'Onitsha', 'Umuahia', 'Ado-Ekiti'],
  'North Macedonia': ['Skopje', 'Bitola', 'Kumanovo', 'Tetovo', 'Ohrid', 'Veles', 'Strumica', 'Prilep', 'Gostivar'],
  'Norway': ['Oslo', 'Bergen', 'Stavanger', 'Trondheim', 'Drammen', 'Fredrikstad', 'Kristiansand', 'Sandnes', 'Tromso', 'Sarpsborg', 'Skien', 'Alesund', 'Sandefjord', 'Haugesund', 'Tonsberg', 'Bodo'],
  'Oman': ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Ibri', 'Saham', 'Barka', 'Rustaq'],
  'Pakistan': ['Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Islamabad', 'Gujranwala', 'Peshawar', 'Multan', 'Hyderabad', 'Quetta', 'Sargodha', 'Sialkot', 'Bahawalpur', 'Sukkur', 'Larkana', 'Sheikhupura', 'Rahim Yar Khan', 'Jhang', 'Dera Ghazi Khan', 'Gujrat', 'Sahiwal', 'Wah Cantonment', 'Mardan', 'Kasur', 'Dera Ismail Khan'],
  'Palestine': ['Gaza', 'Ramallah', 'Hebron', 'Nablus', 'Bethlehem', 'Jenin', 'Tulkarm', 'Qalqilya', 'Jericho', 'Khan Yunis', 'Rafah', 'Deir al-Balah'],
  'Panama': ['Panama City', 'San Miguelito', 'Tocumen', 'David', 'Colon', 'La Chorrera', 'Santiago', 'Arraijan', 'Chitre', 'Bocas del Toro'],
  'Papua New Guinea': ['Port Moresby', 'Lae', 'Mount Hagen', 'Madang', 'Goroka', 'Wewak', 'Kimbe', 'Bulolo', 'Popondetta'],
  'Paraguay': ['Asuncion', 'Ciudad del Este', 'San Lorenzo', 'Luque', 'Capiata', 'Lambare', 'Fernando de la Mora', 'Encarnacion', 'Mariano Roque Alonso', 'Caaguazu', 'Concepcion'],
  'Peru': ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Cusco', 'Huancayo', 'Chimbote', 'Pucallpa', 'Tacna', 'Ica', 'Juliaca', 'Sullana', 'Ayacucho', 'Cajamarca', 'Huanuco', 'Tarapoto', 'Puno', 'Tumbes'],
  'Philippines': ['Manila', 'Quezon City', 'Cebu City', 'Davao', 'Makati', 'Baguio', 'Iloilo', 'Pasig', 'Zamboanga', 'Cagayan de Oro', 'Taguig', 'Antipolo', 'Pasay', 'Caloocan', 'Paranaque', 'Dasmariñas', 'Valenzuela', 'Bacolod', 'General Santos', 'Tacloban', 'Olongapo', 'Butuan', 'Iligan', 'Puerto Princesa'],
  'Poland': ['Warsaw', 'Krakow', 'Lodz', 'Wroclaw', 'Poznan', 'Gdansk', 'Szczecin', 'Katowice', 'Lublin', 'Bydgoszcz', 'Bialystok', 'Torun', 'Radom', 'Rzeszow', 'Kielce', 'Olsztyn', 'Gliwice', 'Zabrze', 'Czestochowa'],
  'Portugal': ['Lisbon', 'Porto', 'Braga', 'Setubal', 'Coimbra', 'Funchal', 'Vila Nova de Gaia', 'Amadora', 'Almada', 'Agualva-Cacem', 'Faro', 'Leiria', 'Viseu', 'Guimaraes', 'Aveiro', 'Evora'],
  'Puerto Rico': ['San Juan', 'Bayamon', 'Carolina', 'Ponce', 'Caguas', 'Guaynabo', 'Mayaguez', 'Arecibo', 'Toa Baja', 'Aguadilla'],
  'Qatar': ['Doha', 'Al Rayyan', 'Al Wakrah', 'Al Khor', 'Umm Salal', 'Al Daayen', 'Mesaieed', 'Dukhan'],
  'Romania': ['Bucharest', 'Cluj-Napoca', 'Timisoara', 'Iasi', 'Constanta', 'Craiova', 'Brasov', 'Galati', 'Ploiesti', 'Oradea', 'Braila', 'Arad', 'Pitesti', 'Sibiu', 'Bacau', 'Targu Mures', 'Baia Mare', 'Buzau', 'Botosani', 'Satu Mare'],
  'Russia': ['Moscow', 'Saint Petersburg', 'Novosibirsk', 'Yekaterinburg', 'Kazan', 'Nizhny Novgorod', 'Chelyabinsk', 'Samara', 'Ufa', 'Rostov-on-Don', 'Krasnoyarsk', 'Perm', 'Voronezh', 'Volgograd', 'Krasnodar', 'Saratov', 'Tyumen', 'Tolyatti', 'Izhevsk', 'Barnaul', 'Ulyanovsk', 'Irkutsk', 'Khabarovsk', 'Vladivostok', 'Yaroslavl'],
  'Saudi Arabia': ['Riyadh', 'Jeddah', 'Mecca', 'Medina', 'Dammam', 'Khobar', 'Tabuk', 'Taif', 'Buraidah', 'Khamis Mushait', 'Abha', 'Hail', 'Najran', 'Jubail', 'Yanbu', 'Al Khafj'],
  'Senegal': ['Dakar', 'Touba', 'Thies', 'Rufisque', 'Kaolack', 'Ziguinchor', 'Saint-Louis', 'Mbour', 'Diourbel'],
  'Serbia': ['Belgrade', 'Novi Sad', 'Nis', 'Kragujevac', 'Subotica', 'Zrenjanin', 'Pancevo', 'Cacak', 'Novi Pazar', 'Kraljevo', 'Smederevo', 'Leskovac', 'Uzice', 'Vranje'],
  'Singapore': ['Singapore', 'Jurong', 'Tampines', 'Woodlands', 'Bedok', 'Sengkang', 'Hougang', 'Yishun', 'Bukit Merah', 'Ang Mo Kio', 'Toa Payoh', 'Clementi'],
  'Slovakia': ['Bratislava', 'Kosice', 'Presov', 'Zilina', 'Banska Bystrica', 'Nitra', 'Trnava', 'Martin', 'Trencin', 'Poprad'],
  'Slovenia': ['Ljubljana', 'Maribor', 'Celje', 'Kranj', 'Koper', 'Velenje', 'Novo Mesto', 'Ptuj', 'Trbovlje', 'Kamnik'],
  'Somalia': ['Mogadishu', 'Hargeisa', 'Berbera', 'Kismayo', 'Merca', 'Baidoa', 'Galkayo', 'Bosaso', 'Beledweyne', 'Garowe'],
  'South Africa': ['Johannesburg', 'Cape Town', 'Durban', 'Pretoria', 'Port Elizabeth', 'Bloemfontein', 'East London', 'Soweto', 'Pietermaritzburg', 'Benoni', 'Tembisa', 'Centurion', 'Vereeniging', 'Kimberley', 'Rustenburg', 'Polokwane', 'Nelspruit', 'George', 'Stellenbosch'],
  'South Korea': ['Seoul', 'Busan', 'Incheon', 'Daegu', 'Daejeon', 'Gwangju', 'Suwon', 'Ulsan', 'Changwon', 'Seongnam', 'Goyang', 'Yongin', 'Bucheon', 'Cheongju', 'Ansan', 'Jeonju', 'Anyang', 'Cheonan', 'Pohang', 'Jeju'],
  'Spain': ['Madrid', 'Barcelona', 'Valencia', 'Seville', 'Zaragoza', 'Malaga', 'Murcia', 'Palma', 'Bilbao', 'Alicante', 'Cordoba', 'Valladolid', 'Vigo', 'Gijon', 'Granada', 'A Coruna', 'Vitoria-Gasteiz', 'Elche', 'Oviedo', 'Santa Cruz de Tenerife', 'Cartagena', 'Jerez de la Frontera', 'Pamplona', 'Almeria', 'Salamanca', 'Leon', 'Huelva'],
  'Sri Lanka': ['Colombo', 'Kandy', 'Galle', 'Jaffna', 'Negombo', 'Trincomalee', 'Batticaloa', 'Anuradhapura', 'Ratnapura', 'Matara', 'Badulla', 'Kurunegala'],
  'Sudan': ['Khartoum', 'Omdurman', 'Khartoum North', 'Port Sudan', 'Kassala', 'Nyala', 'El Fasher', 'Wad Madani', 'Kosti', 'Gedaref', 'El Obeid'],
  'Sweden': ['Stockholm', 'Gothenburg', 'Malmo', 'Uppsala', 'Vasteras', 'Orebro', 'Linkoping', 'Helsingborg', 'Jonkoping', 'Norrkoping', 'Lund', 'Umea', 'Gavle', 'Boras', 'Sodertalje', 'Eskilstuna', 'Karlstad', 'Halmstad', 'Vaxjo'],
  'Switzerland': ['Zurich', 'Geneva', 'Basel', 'Bern', 'Lausanne', 'Winterthur', 'Lucerne', 'St. Gallen', 'Lugano', 'Biel', 'Thun', 'Fribourg', 'Schaffhausen', 'Chur', 'Neuchatel', 'Uster', 'Sion'],
  'Syria': ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Raqqa', 'Deir ez-Zor', 'Hasakeh', 'Tartus', 'Daraa', 'Idlib'],
  'Taiwan': ['Taipei', 'Kaohsiung', 'Taichung', 'Tainan', 'Hsinchu', 'Taoyuan', 'Keelung', 'Chiayi', 'Hualien', 'Taitung', 'Yilan', 'Miaoli', 'Changhua', 'Nantou', 'Pingtung', 'Yunlin'],
  'Tajikistan': ['Dushanbe', 'Khujand', 'Kulob', 'Bokhtar', 'Istaravshan', 'Konibodom', 'Tursunzoda', 'Isfara'],
  'Tanzania': ['Dar es Salaam', 'Mwanza', 'Arusha', 'Dodoma', 'Mbeya', 'Morogoro', 'Tanga', 'Tabora', 'Kigoma', 'Iringa', 'Songea', 'Moshi', 'Bukoba', 'Zanzibar City', 'Tunduma'],
  'Thailand': ['Bangkok', 'Chiang Mai', 'Phuket', 'Pattaya', 'Hat Yai', 'Khon Kaen', 'Nakhon Ratchasima', 'Udon Thani', 'Chiang Rai', 'Nonthaburi', 'Pak Kret', 'Surat Thani', 'Nakhon Si Thammarat', 'Rayong', 'Lampang', 'Ubon Ratchathani', 'Phitsanulok', 'Songkhla', 'Kanchanaburi', 'Ayutthaya'],
  'Timor-Leste': ['Dili', 'Baucau', 'Maliana', 'Suai', 'Lospalos', 'Ainaro', 'Ermera'],
  'Tunisia': ['Tunis', 'Sfax', 'Sousse', 'Ettadhamen', 'Kairouan', 'Gabes', 'Bizerte', 'Ariana', 'Gafsa', 'Kasserine', 'Monastir', 'Ben Arous', 'M\'saken', 'Houmt Souk'],
  'Turkey': ['Istanbul', 'Ankara', 'Izmir', 'Bursa', 'Adana', 'Gaziantep', 'Antalya', 'Konya', 'Trabzon', 'Diyarbakir', 'Mersin', 'Eskisehir', 'Kayseri', 'Denizli', 'Samsun', 'Sanliurfa', 'Malatya', 'Kahramanmaras', 'Van', 'Batman', 'Elazig', 'Erzurum', 'Manisa', 'Balikesir', 'Sivas', 'Tekirdag', 'Edirne', 'Aydin', 'Aksaray', 'Isparta'],
  'Turkmenistan': ['Ashgabat', 'Turkmenabat', 'Mary', 'Turkmenbashi', 'Balkanabat', 'Dashoguz', 'Bayramaly'],
  'Uganda': ['Kampala', 'Gulu', 'Lira', 'Mbarara', 'Jinja', 'Mbale', 'Mukono', 'Masaka', 'Entebbe', 'Fort Portal', 'Soroti', 'Arua', 'Kabale', 'Hoima'],
  'Ukraine': ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Donetsk', 'Zaporizhzhia', 'Lviv', 'Mykolaiv', 'Mariupol', 'Luhansk', 'Vinnytsia', 'Khmelnytskyi', 'Chernivtsi', 'Poltava', 'Chernihiv', 'Sumy', 'Zhytomyr', 'Rivne', 'Ivano-Frankivsk', 'Ternopil', 'Lutsk', 'Uzhhorod', 'Kropyvnytskyi', 'Kremenchuk'],
  'United Arab Emirates': ['Dubai', 'Abu Dhabi', 'Sharjah', 'Al Ain', 'Ajman', 'Ras Al Khaimah', 'Fujairah', 'Umm Al Quwain', 'Khor Fakkan'],
  'United Kingdom': ['London', 'Birmingham', 'Manchester', 'Glasgow', 'Leeds', 'Liverpool', 'Sheffield', 'Edinburgh', 'Bristol', 'Cardiff', 'Belfast', 'Newcastle', 'Nottingham', 'Leicester', 'Coventry', 'Bradford', 'Hull', 'Stoke-on-Trent', 'Wolverhampton', 'Plymouth', 'Derby', 'Swansea', 'Aberdeen', 'Southampton', 'Portsmouth', 'Brighton', 'Reading', 'Oxford', 'Cambridge', 'Milton Keynes', 'Dundee'],
  'United States': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'San Francisco', 'Columbus', 'Charlotte', 'Indianapolis', 'Seattle', 'Denver', 'Washington', 'Nashville', 'Boston', 'Portland', 'Las Vegas', 'Miami', 'Atlanta', 'Minneapolis', 'New Orleans', 'Detroit', 'Memphis', 'Baltimore', 'Milwaukee', 'Tampa', 'Orlando', 'Pittsburgh', 'Cincinnati', 'St. Louis', 'Cleveland', 'Kansas City', 'Sacramento', 'Salt Lake City', 'Raleigh', 'Richmond', 'Hartford', 'Honolulu', 'Anchorage', 'Boise', 'Charleston', 'Savannah', 'Madison', 'Omaha', 'Albuquerque', 'El Paso', 'Tucson', 'Fresno', 'Mesa', 'Long Beach', 'Oakland', 'Tulsa', 'Omaha', 'Tucson'],
  'Uruguay': ['Montevideo', 'Salto', 'Ciudad de la Costa', 'Paysandu', 'Las Piedras', 'Rivera', 'Maldonado', 'Tacuarembo', 'Melo', 'Artigas', 'Minas'],
  'Uzbekistan': ['Tashkent', 'Samarkand', 'Namangan', 'Andijan', 'Bukhara', 'Nukus', 'Fergana', 'Karakalpakstan', 'Kokand', 'Margilan', 'Jizzakh', 'Urgench', 'Termez', 'Navoiy', 'Gulistan'],
  'Venezuela': ['Caracas', 'Maracaibo', 'Valencia', 'Barquisimeto', 'Maracay', 'Ciudad Guayana', 'Barcelona', 'Maturin', 'Cumana', 'San Cristobal', 'Merida', 'Ciudad Bolivar', 'Puerto La Cruz', 'Los Teques', 'Guarenas'],
  'Vietnam': ['Hanoi', 'Ho Chi Minh City', 'Da Nang', 'Hai Phong', 'Can Tho', 'Hue', 'Nha Trang', 'Vung Tau', 'Bien Hoa', 'Bac Ninh', 'Quy Nhon', 'Buon Ma Thuot', 'Thai Nguyen', 'Nam Dinh', 'Ha Long', 'Vinh', 'Long Xuyen', 'Rach Gia', 'My Tho', 'Da Lat'],
  'Yemen': ['Sanaa', 'Aden', 'Taiz', 'Hodeidah', 'Ibb', 'Dhamar', 'Al Mukalla', 'Amran', 'Zinjibar', 'Sayyan'],
  'Zimbabwe': ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Epworth', 'Kwekwe', 'Kadoma', 'Masvingo', 'Victoria Falls'],
};

/// 250 negara lengkap untuk filter online users
const List<String> allCountries = [
  'Afghanistan', 'Albania', 'Algeria', 'Angola', 'Argentina', 'Armenia',
  'Australia', 'Austria', 'Azerbaijan', 'Bahrain', 'Bangladesh', 'Belarus',
  'Belgium', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Brazil', 'Brunei',
  'Bulgaria', 'Burkina Faso', 'Cambodia', 'Cameroon', 'Canada', 'Chile',
  'China', 'Colombia', 'Costa Rica', 'Cote d\'Ivoire', 'Croatia', 'Cuba',
  'Cyprus', 'Czech Republic', 'Denmark', 'Dominican Republic', 'Ecuador', 'Egypt',
  'El Salvador', 'Estonia', 'Ethiopia', 'Fiji', 'Finland', 'France',
  'Georgia', 'Germany', 'Ghana', 'Greece', 'Guatemala', 'Haiti',
  'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia',
  'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
  'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kosovo', 'Kuwait',
  'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Libya', 'Lithuania',
  'Luxembourg', 'Macau', 'Madagascar', 'Malaysia', 'Maldives', 'Mali',
  'Malta', 'Mexico', 'Moldova', 'Mongolia', 'Montenegro', 'Morocco',
  'Mozambique', 'Myanmar', 'Nepal', 'Netherlands', 'New Zealand', 'Niger',
  'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palestine',
  'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
  'Portugal', 'Puerto Rico', 'Qatar', 'Romania', 'Russia', 'Saudi Arabia',
  'Senegal', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'Somalia',
  'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sudan', 'Sweden',
  'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
  'Timor-Leste', 'Tunisia', 'Turkey', 'Turkmenistan', 'Uganda', 'Ukraine',
  'United Arab Emirates', 'United Kingdom', 'United States', 'Uruguay', 'Uzbekistan',
  'Venezuela', 'Vietnam', 'Yemen', 'Zimbabwe',
];

/// Mendapatkan list kota untuk negara tertentu
List<String> getCitiesForCountry(String country) =>
    kotaByNegara[country] ?? [];

/// Mendapatkan nama negara (kompatibilitas dengan entry_screen)
String negaraLabel(String key, bool isId) => key;

/// Mendapatkan list negara yang punya data kota
List<String> getNegaraKeys() => kotaByNegara.keys.toList();
